/**
 * Standard API error codes. The frontend matches against these strings to
 * decide UI treatment (toast vs inline vs redirect) — keep stable.
 */
export const ERROR_CODES = {
  // Auth / session
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  VERIFICATION_FLAGGED: 'VERIFICATION_FLAGGED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_MATRIC: 'INVALID_MATRIC',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
  REUPLOAD_LIMIT_REACHED: 'REUPLOAD_LIMIT_REACHED',
  REUPLOAD_COOLDOWN_ACTIVE: 'REUPLOAD_COOLDOWN_ACTIVE',

  // Team
  TEAM_LOCKED: 'TEAM_LOCKED',
  TEAM_FULL: 'TEAM_FULL',
  TEAM_TOO_SMALL: 'TEAM_TOO_SMALL',
  ALREADY_IN_TEAM: 'ALREADY_IN_TEAM',
  WRONG_DEPARTMENT: 'WRONG_DEPARTMENT',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  ONLY_LEADER: 'ONLY_LEADER',

  // Submissions
  SUBMISSION_LOCKED: 'SUBMISSION_LOCKED',
  SUBMISSION_WINDOW_CLOSED: 'SUBMISSION_WINDOW_CLOSED',
  STAGE_CLOSED: 'STAGE_CLOSED',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  WORD_LIMIT_EXCEEDED: 'WORD_LIMIT_EXCEEDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_WRONG_DEPARTMENT: 'TOKEN_WRONG_DEPARTMENT',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Default HTTP status code per error code. */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  AUTH_REQUIRED: 401,
  FORBIDDEN: 403,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_SUSPENDED: 403,
  VERIFICATION_PENDING: 403,
  VERIFICATION_REJECTED: 403,
  VERIFICATION_FLAGGED: 403,

  VALIDATION_ERROR: 400,
  INVALID_MATRIC: 400,
  INVALID_FILE_TYPE: 400,
  FILE_TOO_LARGE: 413,

  NOT_FOUND: 404,
  DUPLICATE_ENTRY: 409,

  RATE_LIMITED: 429,
  REUPLOAD_LIMIT_REACHED: 429,
  REUPLOAD_COOLDOWN_ACTIVE: 429,

  TEAM_LOCKED: 403,
  TEAM_FULL: 409,
  TEAM_TOO_SMALL: 409,
  ALREADY_IN_TEAM: 409,
  WRONG_DEPARTMENT: 400,
  INVITE_EXPIRED: 410,
  INVITE_NOT_FOUND: 404,
  ONLY_LEADER: 403,

  SUBMISSION_LOCKED: 403,
  SUBMISSION_WINDOW_CLOSED: 403,
  STAGE_CLOSED: 403,
  ALREADY_SUBMITTED: 409,
  WORD_LIMIT_EXCEEDED: 400,
  INVALID_TOKEN: 400,
  TOKEN_WRONG_DEPARTMENT: 400,

  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
